repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --follow-imports=skip]
        additional_dependencies: [types-requests]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args: [--profile=black]
-   repo: https://github.com/PYCQA/flake8
    rev: 7.1.0
    hooks:
    -   id: flake8
        args: ["--max-line-length=120", "--ignore=W503, E203"]
